Stoccoin-Official/Stoccoin-Website

README.md
package-lock.json

i have made necessary changes in readme file for this bug

fix : Readme start command bug fixed

---

client/src/components/Footer.jsx

Previous Behaviour-
Updated Behaviour-
Changes-
1. Increased the font-weight of Social links and About Us text.
2. Changed the hover color of Social links. (Previously it was white which was not visible on hovered.)
3. Changed the color of the input field in the newsletter section. (Button color and input field color looked the same.)

Improved the UI of the footer section

---

server/package-lock.json
server/package.json

I've added Nodemon to the project, allowing the server to automatically reload whenever there are changes in the server directory. This saves time during development by eliminating the need to manually restart the server after making modifications.

Integrate nodemon

---

README.md

#51 closes.
correct project docs

made changes in docs

---

client/src/components/Footer.jsx

Fixes #102 
1. The social links in footer section now open in new tab.
https://github.com/Stoccoin-Official/Stoccoin-Website/assets/116940083/6ce3f828-0446-46bc-93cf-492485685f86
https://github.com/Stoccoin-Official/Stoccoin-Website/assets/116940083/5ee0b575-c8ae-46dd-8037-7f4531d1d8f7

fix: social links in footer open in new tab

---

GSSoC-CONTRIBUTORS.md

I wish to contribute to this great project. Please allow me to. I have added my name to contributor list as stated in GSSoC-contributors.md

docs: Added name to contributor list

---

client/package-lock.json
client/src/components/Accordion.jsx
client/src/components/ContactForm.jsx
client/src/components/Features.jsx
client/src/components/Header.jsx
client/src/components/Navbar.jsx
client/src/components/Pricing.jsx
client/src/components/Stats.jsx
package-lock.json
package.json

Linked all the nav links to different sections
please accept my PR

Linked Routes

---

GSSoC-CONTRIBUTORS.md

Hi @royalpinto007, I have added my name and college in Gssoc23 contributors list.

docs: added my name and college in gssoc contributors list

---

client/package-lock.json
client/src/components/Accordion.jsx
client/src/components/ContactForm.jsx
client/src/components/Features.jsx
client/src/components/Header.jsx
client/src/components/Navbar.jsx
client/src/components/Pricing.jsx
client/src/components/Stats.jsx
package-lock.json
package.json

Reverts Stoccoin-Official/Stoccoin-Website#112

Revert "fix: Linked Routes"

---

client/src/components/Pricing.jsx

fixes #107 
Now the cards have a nice hover and shadow effect on them

feat: Added hovereffect to pricing cards

---

client/package-lock.json
client/package.json
client/src/components/ContactForm.jsx
package-lock.json
server/App.js
server/package-lock.json
server/package.json
server/routes/mail.js

With this enhancement, the Contact Requests from the from will be sent to the owner's Email. This is efficient as user won't need to store contact data to the database.
#168 
https://github.com/Stoccoin-Official/Stoccoin-Website/assets/90945182/16311e5c-475f-4656-b6e5-d9685851676b

[Feature] Added SMTP server to send Contact Form Data

---

client/src/components/Navbar.jsx

Fixes #105 
Added hover effects on navlinks in desktop view similar to that of tablet and mobile view.
https://github.com/Stoccoin-Official/Stoccoin-Website/assets/116940083/f4f9c35b-bf09-443c-8b47-e1b077e900b4
https://github.com/Stoccoin-Official/Stoccoin-Website/assets/116940083/8fc60fc5-be7b-4073-8829-a3759839fe79

feat: Added hover effects for links in navbar

---

client/src/components/Header.jsx

closes #90 
Desktop - 
Tablet - 
Mobile -

Feat: Added Responsiveness to Hero Section

---

GSSoC-CONTRIBUTORS.md

Fixes #155 
Added the details of contributors in tabular form in GSSOC-CONTRIBUTORS file.

chore: Add tabular data format in GSSOC-CONTRIBUTORS.md file

---

client/src/components/Footer.jsx

Fixes #163 
1. The text visibility and UI of the contact us form is improved for seamless user exprience.
https://github.com/Stoccoin-Official/Stoccoin-Website/assets/116940083/e0933153-7731-440b-a65c-03f40d5005b0
https://github.com/Stoccoin-Official/Stoccoin-Website/assets/116940083/e5a075a2-2d8c-4497-977f-bb9c0b7e9d90

fix: Improved the text visibility and UI in contact usform

---

GSSoC-CONTRIBUTORS.md

I am actively participating in GSSoC23 as a contributor and I have a strong inclination towards this project.

docs: Add Name to Gssoc'23 Contributors

---

client/package-lock.json
client/package.json
client/src/App.jsx
client/src/components/Navbar.jsx
client/src/pages/Cryptocurrencies.jsx
client/src/pages/Dashboard.jsx
client/src/pages/Derivatives.jsx
client/src/pages/Homepage.jsx
client/src/pages/Institutional.jsx
client/src/pages/NFT.jsx
client/src/pages/News.jsx
client/src/pages/Stocks.jsx
client/src/pages/Support.jsx
client/src/pages/Trade.jsx

Fixes #181 
The navlinks route to their respective pages.
> Note: There is no appropriate content an these pages yet. They are just initialized and the content will be added soon.
I have updated the file structure for `/client/src` directory as follows:
```yaml
client/src:
- assets/
- components/
- pages:
- Cryptocurrencies.jsx
- Dashboard.jsx
- Derivates.jsx
- Homepage.jsx
- Institutional.jsx
- News.jsx
- NFT.jsx
- Stocks.jsx
- Support.jsx
- Trade.jsx
```
https://github.com/Stoccoin-Official/Stoccoin-Website/assets/116940083/77bb22cb-2c9a-44dd-9d20-75a4a5b8a710

feat: Add pages for navlinks

---

README.md
client/src/App.jsx

Fixes #184 
The below rule is added in the README.md file-
>Contributors must finish their work for an issue within 4-5 days if they are either assigned or have shown interest in solving the issue to avoid conflicts.

docs: Add contributing rule in README.md

---

GSSoC-CONTRIBUTORS.md

@royalpinto007 
I've added my name and college in the GSSoC contributors markdown file. I kindly request the repository maintainers to review and merge the pull request.
Thanks.

docs: Update GSSoC-CONTRIBUTORS.md

---

GSSoC-CONTRIBUTORS.md

Hello,
I am a contributor in GSSOC 2023. I am interested in contributing on various issues in the project, considering my extensive experience of working with MERN stack, I suggest to add my name and college to GSSoC-CONTRIBUTORS.md.
Thank you

Added my name and college to GSSoC-CONTRIBUTORS.md

---

GSSoC-CONTRIBUTORS.md

Added name and college to the GSSoC-CONTRIBUTORS.md file.

docs: Added name to GSSoC-Contributors.md

---

GSSoC-CONTRIBUTORS.md

I have added my name to the contributors list.

name added to list

---

client/src/App.css
client/src/components/Navbar.jsx

close #44 
Desktop View -
https://github.com/Stoccoin-Official/Stoccoin-Website/assets/115306535/9cab942a-f3d9-4eb1-afd5-47557a628c68
Mobile - 
https://github.com/Stoccoin-Official/Stoccoin-Website/assets/115306535/07bc9863-3b5c-4e58-90c8-42d423915561

Feat: Implement Responsive Navigation Bar and Sidebar

---

client/src/components/Footer.jsx

Added the social icons

---

client/package-lock.json
client/package.json
client/src/components/Header.jsx
client/src/components/Modal.jsx
client/src/components/Navbar.jsx
client/src/pages/Homepage.jsx

- Fixes #159 and #198
- Partially fixes #50 by implementing the `Login ModalUI` in this PR.
1. Created a fully responsive `Login Page UI` for the website.
2. User can login to the website using `email` and `password`.
3. The `Login modal` can be close by clicking on the `close-icon` or clicking anywhere outside the modal on the screen.
1. Improved the spacing of `navbar-links`.
2. Added hover effect for the `Login` button.
This design is made with guidance of @royalpinto007 .  
https://github.com/Stoccoin-Official/Stoccoin-Website/assets/116940083/32b97e4e-4d98-4d80-ba90-70617e8f0ba4

feat: Create a Login UI for the website

---

Education/stocks-introduction.md

Closes #55 
Populated the `stocks-introduction.md` file as mentioned in the issue.
- Table of Contents
- Introduction to Stocks
- What are stocks
- Why companies issue stocks
- Examples of well know stocks *(in tabular form)*
- Stock Market
- Key terminology
- How stocks functions as investment vehicles
- Stock Exchanges
- Key features and functions of stock exchanges
- Prominent stock exchanges

docs: Populated introduction to stocks

---

Education/cryptocurrencies-introduction.md

Added information and explanations to Education/cryptocurrencies-introduction.md. Included introduction to blockchain technology, web3.0 and examples. Also included the risks/benefits of investing in crypto.

Added info to cryptocurrency introduction

---

README.md

Added link for redirection to contribute.md

Redirecting from Readme to Contributing.md GSSOC'23

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

Resolves issue #251 
Added Pull Request template in .md format.

Added pull request template

---

GSSoC-CONTRIBUTORS.md

Hello!!!, I have gone through all the steps necessary for contribution. I have created firstcontribution/add-name branch & added my name & college name in the list of contributors. 
Please review my pull request & approve it.

added name & college name

---

Education/tax-implications.md

This pull request address #65. I kindly request the repository maintainers to review and merge the pull request. Your attention and assistance in resolving this matter are greatly appreciated.
Thanks.

[GSSoC '23] docs: Update tax-implications.md

---

Education/investment-strategies.md

This pull request address #64. I kindly request the repository maintainers to review and merge the pull request. Your attention and assistance in resolving this matter are greatly appreciated.
Thanks.

[GSSoC '23] docs: Update investment-strategies.md

---

GSSoC-CONTRIBUTORS.md

I was not active due to college activities. Thus, I forgot to add my name. 
https://github.com/Stoccoin-Official/Stoccoin-Website/issues/115#issuecomment-1560014067

feat: Added name to GSSOC-Contributors

---

Education/stock-market-basics.md

Fixes #57 
- Populated `stock-market-basics.md` file
- Added content for **stock market**, **stock exchanges**, **stock indices**, **stock prices**, with appropriate examples.

docs: Populated stock-market-basics.md file

---

Education/stocks-introduction.md
Education/types-of-stocks.md

Fixes #59 
- Populated the `types-of-stocks.md` file as per the given instruction.
- Types covered
- Common stocks
- Preferred stocks
- Value stocks
- Growth stocks
- Dividend stocks
- Large-Cap, Mid-Cap and Small-Cap stocks
- For each type I have covered their **characteristics**, **risks**, **benefits** and **examples**.

docs: populated types-of-stocks.md file

---

client/src/components/Navbar.jsx

I have added Forgot Password Page which is matching with the theme. 
Kindly check this PR and let me know the changes if any

Added Show forgot Password Page

---

Education/resources-and-tools.md

Fixes #286 
- Populated `resources-and-tools.md` file with appropriate tools and resources.
- For each sub-section resources are added in tabular form with `resource`, `description` and `link` in each table.
- Stock Market
- Financial News websites
- Stock exchanges
- Online brokers
- Fundamental analysis tools
- technical analysis tools
- Cryptocurrencies
- News platforms
- Crypto exchanges
- Wallets
- Social trading platforms

feat: populated resources-and-tools.md file

---

GSSoC-CONTRIBUTORS.md

Hi @royalpinto007 , I have made changes to the  GSSoC-CONTRIBUTORS.md file. Kindly review and accept my PR

feat: added name and college name to GSSoC-CONTRIBUTORS.md

---

client/src/pages/Dashboard.jsx
client/src/pages/Derivatives.jsx
client/src/pages/Institutional.jsx
client/src/pages/NFT.jsx
client/src/pages/News.jsx
client/src/pages/Support.jsx
client/src/pages/Trade.jsx

feat:add footer to pending pages

---

GSSoC-CONTRIBUTORS.md

Updated the file GSSoC-CONTRIBUTORS.md

added the name and college in file

---

client/src/App.css
client/src/App.jsx

Closes #322 
Add proper code spliting with React lazy and suspense with proper fallback.

feat: Add Code Spliting

---

client/package-lock.json
client/package.json
client/src/components/Footer.jsx

This PR adds a toast notification for a successful subscription in the footer component. It provides feedback to the user when they submit their email for the newsletter, indicating that the subscription was successful.
Fixes #317 
- New feature (non-breaking change which adds functionality)

feat: Add toast notification for successful subscription in footer component

---

client/src/components/Accordion.jsx

Added scrolling for users to be redirected to "Get in Touch" form after clicking "Contact Us"

Issue 332, added scroll for Contact Us

---

client/src/components/Accordion.jsx

- Added QnA component to display frequently asked questions.
- Added interactivity to expand and collapse question answers.

refactor: made accordion interactive

---

.github/workflows/lock-issues.yml

Fixes/Closes: #357 
Added github action workflow to lock new issues.
- `.github/workflows/lock-issues.yml`
What sort of change have you made:
@royalpinto007 Please review this PR
Thanks.

feat: add github action to lock new issues

---

client/src/components/Pricing.jsx

Fixes #166
The pricing cards now have smooth animation for seamless user experience on all devices- desktop, table and moblie.
https://github.com/Stoccoin-Official/Stoccoin-Website/assets/116940083/e36298fe-100f-4c8f-b622-35b0f5f2b735
https://github.com/Stoccoin-Official/Stoccoin-Website/assets/116940083/a8428c15-4cd5-445b-8ebf-f459d168c904

fix: Add animation to pricing card

---

app/public/sitemap.xml

[ADDED]: sitemap.xml

---

app/src/components/Navbar.jsx
app/src/pages/Login.jsx

- add: dark mode for responsive site, dark mode to the components used for mobile view
- refactor code based on the changes needed.

feat: dark mode for responsive site

---

.github/ISSUE_TEMPLATE/documentation.yml

- **Rectifying Minor Indentation Problems in documentation.yml File.**
- **After the Changes Made, It works Fine.**
- **Please Review on this PR.**

fix: Resolved Error in documentation.yml File

---

.github/ISSUE_TEMPLATE/styles.yml

- **Added styles.yml File for Raising Code Style and Enhancement Related Issues and Requests in GitHub Issues Templates List.**
- **Please Take a Review on this PR.**

feat: Added styles.yml File in ISSUE TEMPLATES List

---

README.md

Fixes- https://github.com/Stoccoin-Official/Stoccoin-Website/issues/415

fix: getting started instructions

---

README.md

fix: Tech Stack in Documentation
